# Generated by Django 5.2.15 on 2026-06-19 15:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Введите номер в международном формате, например: +79161234567', max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
