# Generated by Django 5.2.15 on 2026-06-19 16:21

from django.db import migrations
from phonenumbers import parse, format_number, PhoneNumberFormat, is_valid_number

def normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed = parse(flat.owners_phonenumber, 'RU')
                if is_valid_number(parsed):
                    flat.owner_pure_phone = format_number(parsed, PhoneNumberFormat.INTERNATIONAL)
                    flat.save()
            except Exception:
                pass

def reverse_normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=None)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, reverse_normalize_phones),
    ]
