# Generated by Django 5.2.15 on 2026-06-19 16:53

from django.db import migrations

def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        if flat.owner:
            owner, created = Owner.objects.get_or_create(
                full_name=flat.owner,
                phonenumber=flat.owners_phonenumber,
                defaults={
                    'pure_phone': flat.owner_pure_phone,
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]