# Generated by Django 5.2.15 on 2026-06-19 17:04

from django.db import migrations

def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if flat.owner:
            owner, created = Owner.objects.get_or_create(
                full_name=flat.owner,
                phonenumber=flat.owners_phonenumber,
                defaults={
                    'pure_phone': flat.owner_pure_phone,
                }
            )
            owner.flats.add(flat)

def reverse_link_owners_to_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20260619_1953'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats, reverse_link_owners_to_flats),
    ]